swagger: '2.0'
info:
  description: |
    **Fadhli's SKUs and MetricPollers CRUD**
    
    **Team's app.py**: https://github.com/SerenaGohmez/TEAMRedfish-CRUDs/blob/master/app.py
    **Flask authentication**: sti:sti
    
    **Github page**: https://github.com/SerenaGohmez/TEAMRedfish-CRUDs
    
    **Individual app.py** (SKUs && MetricPollers CRUD Only): https://github.com/Fadhli1998/sti2017/blob/master/app.py
    **Flask authentication**: admin:python
    
    **Github page**: https://github.com/Fadhli1998/sti2017
    
  version: 1.0.0
  title: STI2017
  # put the contact info for your development or API team
  contact:
    email: 1503566J@student.tp.edu.sg

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /login:
    post:
      tags:
      - RackHD Login
      summary: login to RackHD and retrieve API Token
      description: Input username and password to retrieve token
      security:
      - basicAuth: []
      parameters:
      - in: body
        name: credentials
        description: username and password
        required: true
        schema:
          $ref: '#/definitions/credentials'
      responses:
        200:
          description: List of SKUs retrieved
        400:
          description: bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error
  
  
  /skus/read:
    get:
      tags:
      - SKUs CRUD
      summary: Read a list of SKUs
      operationId: readSKUs
      description: |
        Get a list of SKUs by passing the authentication token
      produces:
      - application/json
      parameters:
      - in: header
        name: content-type
        description: Indicate media type of resource e.g. application/json
        required: true
        type: string  
      - in: header
        name: token
        description: Pass a token to validate authentication
        required: true
        type: string
      responses:
        200:
          description: List of SKUs retrieved
        400:
          description: bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error
          
  /skus/create:
    post:
      tags:
      - SKUs CRUD
      summary: Create a New SKU
      operationId: createSKUs
      description: |
        Creates a New SKU
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: data
        description: SKU data 
        schema:
          $ref: '#/definitions/skus_create'
      - in: header
        name: content-type
        description: Indicate media type of resource e.g. application/json
        required: true
        type: string
      - in: header
        name: token
        description: Pass a token to validate authentication
        required: true
        type: string
      responses:
        200:
          description: SKU Created
        400:
          description: Bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error

  /skus/update:
    patch:
      tags: 
      - SKUs CRUD
      summary: Update a Single SKU
      operationId: updateSKUs
      description: |
        Updates a single SKU
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: skuId
        description: SKU id to update
        required: true
        type: string
      - in: body
        name: data
        description: SKU data to update
        schema:
          $ref: '#/definitions/skus_update'
      - in: header
        name: content-type
        description: Indicate media type of resource e.g. application/json
        required: true
        type: string
      - in: header
        name: token
        description: Pass a token to validate authentication
        required: true
        type: string    
      responses:
        200:
          description: SKU Updated
        400:
          description: Bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error   
          
  /skus/delete:
    delete:
      tags: 
      - SKUs CRUD
      summary: Delete a Single SKU
      operationId: deleteSKUs
      description: |
        Deletes a single SKU
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: skuId
        description: SKU id to delete
        required: true
        schema:
          $ref: '#/definitions/skus_delete'
      - in: header
        name: content-type
        description: Indicate media type of resource e.g. application/json
        required: true
        type: string
      - in: header
        name: token
        description: Pass a token to validate authentication
        required: true
        type: string    
      responses:
        200:
          description: SKU Deleted
        400:
          description: Bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error

  /metricpollers/read:
    get:
      tags:
      - Metric Pollers CRUD
      summary: Read a list of pollers
      operationId: readmetricpollers
      description: |
        Get a list of pollers by passing the authentication token
      produces:
      - application/json
      parameters:
      - in: header
        name: content-type
        description: Indicate media type of resource e.g. application/json
        required: true
        type: string  
      - in: header
        name: token
        description: Pass a token to validate authentication
        required: true
        type: string
      responses:
        200:
          description: List of pollers retrieved
        400:
          description: bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error

  /metricpollers/create:
    post:
      tags:
      - Metric Pollers CRUD
      summary: Create a New Metric Poller
      operationId: createmetricpollers
      description: |
        Creates a New Metric Poller
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: data
        description: Metric Poller data 
        schema:
          $ref: '#/definitions/metricpollers_create'
      - in: header
        name: content-type
        description: Indicate media type of resource e.g. application/json
        required: true
        type: string  
      - in: header
        name: token
        description: Pass a token to validate authentication
        required: true
        type: string
      responses:
        200:
          description: Metric Poller Created
        400:
          description: Bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error

  /metricpollers/update:
    patch:
      tags: 
      - Metric Pollers CRUD
      summary: Update a Single Metric Poller
      operationId: updatemetricpollers
      description: |
        Updates a single Metric Poller
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: pollerId
        description: Metric Poller id to update
        required: true
        type: string
      - in: body
        name: data
        description: Metric Poller data to update
        schema:
          $ref: '#/definitions/metricpollers_update'
      - in: header
        name: content-type
        description: Indicate media type of resource e.g. application/json
        required: true
        type: string
      - in: header
        name: token
        description: Pass a token to validate authentication
        required: true
        type: string    
      responses:
        200:
          description: Metric Poller Updated
        400:
          description: Bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error

  /metricpollers/delete:
    delete:
      tags: 
      - Metric Pollers CRUD
      summary: Delete a Single Metric Poller
      operationId: deletemetricpollers
      description: |
        Deletes a single Metric Poller
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: pollerId
        description: Metric Poller id to delete
        required: true
        schema:
          $ref: '#/definitions/metricpollers_delete'
      - in: header
        name: content-type
        description: Indicate media type of resource e.g. application/json
        required: true
        type: string
      - in: header
        name: token
        description: Pass a token to validate authentication
        required: true
        type: string    
      responses:
        200:
          description: Metric Poller Deleted
        400:
          description: Bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error

definitions:
  credentials:
    type: object
    required:
    - username
    - password
    properties:
      username:
        type: string
        format: string
        example: sti
      password:
        type: string
        format: string
        example: sti
  skus_create:
    type: object
    required:
    - name
    - contains
    - contain's path
    - equals
    - equal's path
    - discoveryGraphName
    - username
    - password
    - hostname
    properties:
      name:
        type: string
        format: string
        example: Intel 32GB RAM
      contains:
        type: string
        format: string
        example: Intel
      contain's path:
        type: string
        format: string
        example: dmi.Base Board Information.Manufacturer
      equals:
        type: string
        format: string
        example: 32946864kB
      equal's path:
        type: string
        format: string
        example: ohai.dmi.memory.total
      discoveryGraphName:
        type: string
        format: string
        example: Graph.InstallCoreOS
      username:
        type: string
        format: string
        example: testuser
      password:
        type: string
        format: string
        example: hello
      hostname:
        type: string
        format: string
        example: mycoreos
  skus_update:
    type: object
    required:
    - skuId
    - name
    - contains
    - contain's path
    - equals
    - equal's path
    - discoveryGraphName
    - username
    - password
    - hostname
    properties:
      skuId:
        type: string
        format: UUID
        example: 54dbe83a380cc102b61e0f75
      name:
        type: string
        format: string
        example: Intel 32GB RAM
      contains:
        type: string
        format: string
        example: Intel
      contain's path:
        type: string
        format: string
        example: dmi.Base Board Information.Manufacturer
      equals:
        type: string
        format: string
        example: 32946864kB
      equal's path:
        type: string
        format: string
        example: ohai.dmi.memory.total
      discoveryGraphName:
        type: string
        format: string
        example: Graph.InstallCoreOS
      username:
        type: string
        format: string
        example: testuser
      password:
        type: string
        format: string
        example: hello
      hostname:
        type: string
        format: string
        example: mycoreos
  skus_delete:
    type: object
    required: 
    - skuId
    properties:
      skuId:
        type: string
        format: UUID
        example: 54dbe83a380cc102b61e0f75
  metricpollers_create:
    type: object
    required:
    - type
    - pollInterval
    - node
    - metric
    properties:
      type:
        type: string
        format: string
        example: snmp
      pollInterval:
        type: string
        format: string
        example: 1000
      node:
        type: string
        format: UUID
        example: 54daadd764f1a8f1088fdc42
      metric: 
        type: string
        format: string
        example: snmp-interface-bandwidth-utilization
  metricpollers_update:
    type: object
    required: 
    - pollerId
    - type
    - pollInterval
    - node
    - metric
    properties:
      pollerId:
        type: string
        format: UUID
        example: 54dbc0a11eaecfc22a30d59b
      type:
        type: string
        format: string
        example: snmp
      pollInterval:
        type: string
        format: string
        example: 1000
      node:
        type: string
        format: UUID
        example: 54daadd764f1a8f1088fdc42
      metric: 
        type: string
        format: string
        example: snmp-interface-bandwidth-utilization
  metricpollers_delete:
    type: object
    required:
    - pollerId
    properties:
      pollerId:
        type: string
        format: UUID
        example: 54dbc0a11eaecfc22a30d59b
        
securityDefinitions:
  basicAuth:
    type: basic
        
# Added by API Auto Mocking Plugin
host: localhost:5000
basePath: /rackhd/
schemes:
 - http
